apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wistful-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.wistful.io
    - wistful.io
    secretName: wistful-tls
  rules:
  - host: wistful.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wistful-frontend-service
              port:
                number: 80